import type { NextPage } from 'next'
import Head from 'next/head'
import Button from '@material-ui/core/Button';
import styles from '../styles/Home.module.css';
import Image from 'next/image'
import { useState, useCallback } from 'react';

type Fox = {
  image: string;
}

const default_state = {
  image: "https:\/\/randomfox.ca\/images\/99.jpg",
}

const fox_url = "https://randomfox.ca/floof/";

const Home: NextPage = () => {
  const [ fox, setFox ] = useState<Fox>(default_state);
  const onclick = useCallback(
  () => {
    fetch(fox_url)
      .then((r) => r.json())
      .then((j) => setFox(j))
  },[],
  )
  return (
    <div className={styles.container}>
      <Head>
        <title>ランダムキツネ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Image
        src={fox.image} 
        alt="Picture of the author" 
        width={400} 
        height={400}
        objectFit='contain'
      />
      <Button 
        onClick={onclick}
        variant="contained"
        color="primary"
      >
        キツネ！
      </Button>
    </div>
  )
}

export default Home
